### ISSUE TITLE
It seems like doesn't ready for async/await?

### ISSUE THREAD

**Issue by 18601673727** [mjackson/http-client#36]
```
async get(api, params = {}) {
    console.log('start');
    const fetch = createFetch(
      this.stack,
      method('GET'),
      query(params),
    );

    const data = await fetch(api).then(response => {
      return response;
    });

    console.log(data);

    return data;
  }
```
```
start
undefined
```

**Comment by honymissy1** [comment]
async get(api, params = {}) {
    console.log('start');
    const fetch = await createFetch(
      this.stack,
      method('GET'),
      query(params),
    );

    const data = await fetch(api).then(response => {
      return response;
    });

    console.log(data);

    return data;
  }
